FROM ghcr.io/ublue-os/fedora-distrobox:latest

COPY ./toolboxes/fedora-toolbox/packages.fedora /toolbox-packages

RUN dnf -y upgrade && \
    dnf -y install $(<toolbox-packages) && \
    dnf clean all

RUN rm /toolbox-packages
